DROP TABLE IF EXISTS Intellibot.TrainingData;

CREATE DATABASE IF NOT EXISTS Intellibot;

USE Intellibot;

CREATE TABLE IF NOT EXISTS Intellibot.TrainingData
(
dataid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
question TEXT,
answer TEXT
);

#SAMPLE insert statement
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Where can I find HW1?", "You can find it here:http://www.cs.columbia.edu/~jebara/4771/handouts.html");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("In class when we discussed polynomial regression for a 1D variable, I believe it was mentioned that the training error should be decreasing as the order P of the polynomial increases, since a higher-order polynomial can mimic any lower-order polynomial by setting higher weights = 0. However when I run polyreg.m, using the entire data set of problem1.mat as training data, as the orders increase, there are some cases when a higher order run has larger training error than a lower order run, which is contrary to what was said in lecture. Is this something that occurs in practice for high enough orders?", "What you saw in class is true.You should look more closely to the range of values of your data, and keep in mind that numerical inconsistencies might appear. ");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("How to split training and testing data?The errors profiles for various orders of both test and training data seem similar if split that way. Is this ok?", "Yes, this is ok. You should write down such comments in your report.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("For problem 4, the derivative of the empirical loss has terms that have (1 - f) and f as denominators (if I differentiated correctly?), where f = the  predicted value for one specific data point. So f or (1-f) could potentially be zero as theta gets better. In this case, do we just skip these data points then?", "When float values get extremely small (somewhere around 1e-324), Matlab sets them to zero, and you might need to handle 0/0 that is NaN values.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("What is the purpose of the variable q in Problem 1? Where is this derived from?", "It is a technique to control the amount of points when handling the plot.q is the array of x values for the plot, ranging from the min(x) value to the max(x) value, with a step size of max(x) / 300 (see MATLAB docs: Creating and Concatening Matrices-->Generating a Numeric Sequence-->Using colon operator with a step value).");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("For problem 2, my results are showing that the testing error declines with increasing lambda, but more or less flattens out (at least as far as I can tell through the random fluctuations) after lambda ~= 600, and doesn't appear to begin increasing as lambda approaches 1000. I'm not seeing a clear choice for the best lambda.I'm doing 100 trials of randomized 50-50 splits for each lambda, for lambda from 0 to 1000 as suggested.Is this to be expected? Should I increase the number of trials and/or the range of lambda values, or does it seem like I'm doing something else wrong?", "1. Comparisons of different values of ? should be performed on the same training/testing data split 2. The exact value of ? that minimizes testing error is somewhat dependent on the training/testing split. However, there should still be a minimum in the testing data. It may help to plot against ?-1 to make it more visible, as in the slides. If you do so, make sure to label your axes.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 2: Do we not add the ones vector to the 100 dimensional x vector before applying the formula for getting theta?", "Yes, you can do it.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Are we supposed to randomly split the data into two ONCE and use that ONE set of two-fold split data to analyze polynomial degree d (Problem 1) and lambda (Problem 2)? Or are we supposed to repeat the analysis multiple times with different sets of randomly split data?", "It depends on your own choice. Repeating multiple times could be better.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("I have a relatively simple question regarding the plot for problem 2 on the current assignment: when we plot the testing and training risk for varying values of lambda, are we to plot (a) plain-old least squares risk or (b) the regularized least squares risk?", "You should use the original least squares risk. The regularization is used to penalize complex hypotheses in order to prevent overfitting when training models.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Is there ever a situation in which it might be useful to consider the trend of regularized risk (say, when using cross-validation to determine other parameters of complexity in the model)?", "It is extremely unusual to measure and report the test risk with a regularizer included. There are some extreme settings where it may be warranted, for example if you are cross-validating over many other parameters (not just a couple of like the lambda or the order of a polynomial), since then you may risk over-fitting again.");

INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Question 1 extremely large error values: Hi, I've been running the polyreg.m code on the problem 1 data, but it seems that for any degree D that I input I get an incredibly large error value, often in the 21st power range. Does the polyreg.m need to be directly modified for problem 1?","One way to potentially circumvent some numerical errors is to scale the data before running the code. If you scale the inputs and the outputs (by dividing the input by a large number so that it varies between -1 and 1 and by dividing the output by a large number so that it varies between -1 and 1), you will get better numerical behavior in some algorithms. However, be sure to scale your function's output predictions and compare them to the original outputs so that the empirical risk you report is on the same scale as everyone else's.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Question 1 Best Order: When I ran the polyreg.m over a range of orders, I found that the order giving the lowest testing error changed from run to run. I think this is because I split the testing/training data in half randomly, so it changes upon every run. Is this right, or am I doing something else wrong? If the best order changes, how do I determine the best choice of d? Averaging over several choices of d over several runs?","That's a normal thing caused by different ways of splitting data. To select the best order, you can repeat the process several times with randomly splitting data , and then pick the order with lowest error in average.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Can we write our own code for Question 1 and not use Polyreg.m?","That is fine, we are giving you the code to help you get started.The homeworks in this class are like mini-projects so reasonable changes like this are ok.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Can I write my solution(on paper) for problem 3 and the derivation for problem 4, scan and add it to the report? ","Yes, it is ok although not really recommended. If the graders can't read your answers then you'll get no points.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 2 - value of D: Do we consider different values of D for this question? Or we can choose one value and work with it?","You should not use any D values different then one, meaning your raw features.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem1: Definition of cross-validation: Hello,I am kinda lost about cross-validation.Is the following definition of cross-validation correct: n-fold cross-validation: divide the data up into  chunks and train  times, treating a different chunk as the holdout set each time.?If so, do we need to split the test data from the given data in advance, and then split the left data into training data and test data?","In this case where we will be using cross validation to just evaluate our model and not tune parameters or choose between models its OK to just use the whole dataset for cross validation without a separate test set put aside (especially since we have so littleamount of data)Well know that I think about it better we are tuning The grade of the polynomial or lambda depending the exercise but I think we are not supposed to use a separate testing set to evaluate our model at the end.ADD ON: I think you have the basic idea of k-fold cross validation right. Here's how I think about it hopefully it'll help. Let's use k=5 as an example, and say we're trying to find a lambda value, although the same technique could be applied to find a polynomial degree. First we would split the data into 5 equal portions. For each value of lambda we are considering we would train the model 5 different times, each time "holding out" 1/5th of the data to do testing on. We would compute 5 test errors for each value of lambda, each on a different "fold" of the data, specifically the "fold" we didn't use to do fitting. The average of these 5 test errors we would define to be the test error for that particular lambda. We would then iterate to the next value of lambda and repeat. After going through all values for lambda we'd choose the one with the lowest average test error. At this point we could go back and fit the model to the entire data set using our selected value of lambda to find the parameters.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("What should a write up be?Since this is the first time I did an assignment like this, I am not sure how to write the write up. What should a write up contain? The assignment requirement says 'Clearly denote what each function does, which problem it belongs to, and what the inputs and the outputs are' , does this need to be included in the write up?","The write-up should include only what is asked. Don't worry about formalities, when we grade the assignment we are looking for the right answers and right conclusions (or if not, at least the right approach).In terms of code, you don't need to explain your code in detail. Your code must run and actually produce the results you put in the write-up, but generally a single paragraph is enough to explain what are the files you are submitting for that specific problem. If some of these files are MATLAB functions, explain in a sentence what the function does. That's it. ");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Question 4: how do you want the binary classification error to be quantified?","It would be the count of wrong classifications divided by the total number of observations in the training set. We're looking for a percentage here.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("I have a question about problem 4.  The problem asks us to implement a linear logistic regression algorithm, and to show any derivations we need to make for the algorithm.  However, in class we already showed that you cannot derive a closed form solution to minimize empirical risk for logistic loss.  Is problem 4 asking us to show that you cannot derive a closed form solution?","They want you to use gradient descent. Check lecture 3.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("So I think I have gradient descent working - my algorithm seems to behave as it should. However, I get a different theta each time. I know one of the slides said that the R(theta) is convex so gradient descent always converges to the same solution, but I haven't been able to get that to happen. Is there any reason why I might be seeing this? Could I have possibly calculated the gradient incorrectly?","When you are pretty close to the solution, with a large step size you can find yourself 'stepping over' the optimal solution, in that case you might see an increase in the loss function. You can fix that by either reducing the step size so that you can get closer to the solution or reducing the tolerance so that the last step is not taken to begin with.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("I have my regression code in functions, which I call in scripts to load data, set parameters, run iterations of cross-validation, plot figs, etc. Is there any preference for having code be in functions rather than scripts (or vice versa), or is it fine to use either?","It is fine to use either. Use the way that works best for you.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 2 : Which Graph to plot?
The question asks to plot graph of lambda against risk. So should I plot that or should I plot 1/lambda against risk?","You can plot risk x lambda. Also this allows you to plot a data point for ?=0.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Q1: Increasing training error on increasing D.For large values of degree of polynomial (D>20) I am observing an increase in training error which shouldn't be the case. As large degree polynomial should have error less than equal to  lower degree polynomials. Is anybody observing the same behavior in problem 1?","Yes: https://piazza.com/class/ie6b4xkdzne32i?cid=10.No need to go beyond D=20");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Question 1 Task: I want to make sure I understand this correctly.To clarify, am I just trying to write code that tests for which d is the best? Or am i also writing code to see what the best thetas are? The polyreg.m file seems to already find what the best thetas are. However, it says to "Develop code that finds the theta which minimizes the risk". Am I just doing the cross validation part like it says in the beginning of the problem or the whole process of fitting and such? ","You are trying to find the d value that minimizes risk. Then you will report the theta values corresponding to that specific d.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 4 : Initial value of theta: What should I take as the initial value of theta vector? Can I take it as 0?","You should randomly initialize ?");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Gradient computation for q4: For q4, we need to show the derivation for gradient descent.So, do we simplify the equation given in class notes for lecture 3, or take a derivative of the sigmoid function?","Hard to tell exactly what equation you are talking about. You will have to take derivative of the risk and set to zero. This process will involve also taking the derivative of the sigmoid function.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 2: Do we penalize the test error too? (with the additional penalty) You use different values of lambda to get different models and then calculate training error with additional penalty. But what about testing error, how does that work in this problem?","You may view the question named "Question 2, Plotting Risk". Same question.Hope that helps.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Q4: What is binary classification error?Is it the norm( (theta){t+1} - (theta){t} ) or will it be the number of points which were classified incorrectly for an iteration?","See Question 4: how do you want the binary classification error to be quantified?Is the number of points classified incorrectly divided by the number of observations in the dataset.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("How close do we have to get to the linear boundary between the parabola and the line? Should we be able to achieve 0% classification error rate?","It is possible, but not necessarily you have to get to 0% error (the training might take much longer to get to 0% error). Use your good judgement and stop the training in a reasonable time, but you should be very close to 0% error.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("If I made a modification to polyreg.m (eg. removed the plotting code) but left everything else pretty much alone, should I include it in my submission?","It's ok to re-upload the slightly modified polyreg.m. We just don't want folks to upload tons of standard functions (like Steve Gunn's entire codebase) and to upload massive datasets onto Courseworks because it takes up bandwidth and storage.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("I'm having trouble understanding the terminology in problem 1C.  Is each function in C one of c0...c10 so e.g. c1(100) = 1, c1(200) = -1? Thanks!","There are a lot of confusions due to this question.Think of it this way:Alice chooses d points between 1 and 999.Bob attributes a label to each of these points.Alice look into here set of classifiers c0, ..., c9. If the first point is 15 then c1 classifies it as +1, c5 as +1, c2 as -1 etc. If she can classifies the d points as Bob asked, she wins, otherwise Bob wins. If Alice can find d points so that Bob cannot win, it means that the VC dimension is at least d.To prove that the VC dimension of C is inferior to d, you need to prove that whatever d points Alice choses, Bob can always find a ways to win. If it does not help, please come at my OH.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 1B: Just want to make sure what the notation |H| in VC(H) = log2|H| stands for? Thanks","|H| is the size of a hypothesis space, i.e. the total number of hypotheses.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("If possible, could one of the instructors confirm Dec. 15 as the date for our final exam? ","We have tentatively gotten a slot on December 15th but the registrar has not confirmed it yet. Once we have full confirmation, we will let the class know immediately.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Clarification for Problem 2 on hw2.In problem 2 (A) on hw2, we are asked to prove that the kernel matrix K is positive semi-definite; however, in the lecture slides (Topic 6, p. 16), it says that K is positive definite. Can you clarify which of the two is correct, and confirm what we need to prove for the homework problem?","You need to prove it is positive-semidefinite. In contrast to the positive-definite case, the vectors, {?(x)|x?S} may not be linearly independent.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Q2 part(a) clarification. Are we asked to prove Mercer's theorem in one direction first, and then use Mercer's theorem to prove a,b,c,d or are we supposed to just use Mercer's theorem to prove a,b,c,d?","You are asked to prove Mercer's theorem one way and then a,b,c, and d.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 1c: In problem 1c, what is "shattering" defined as?The example given is that the number "778" belongs to class 7 and class 8. Is this considered to be shattered as the number belongs to 2 classes?","https://en.wikipedia.org/wiki/Shattered_set");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Is problem 4 in Hw 2 means that we have to modify some function code in  Steve Gunn’s software package to make our own SVM classifier? or just use same functions in software to find a good setting of parameters that obtain high recognition accuracy?","Just tune the parameters.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Just wondering where are the office hours posted for this course?","http://www.cs.columbia.edu/~jebara/4771/staff.html");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Without giving away too much, is it sufficient in part (B) to write the feature mapping with respect to one-dimensional inputs? Arbitrary n-dimensional inputs seem to be rather nasty to try to express in this manner.I can express the logic up until the point where I actually need to write the feature mapping phi, but I lack the knowledge of notation to make the n-dimensional case succinctly.","You won't get full credit if you derive the solution for 1-dimensional data only. The d-dimensional case is actually not that hard to derive, the feature mapping phi is infinite dimensional for both 1-dimensional and d-dimensional cases and therefore you should think of inner-products as an integral (over the product) rather than a sum (of products).");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("I am having trouble understanding why the VC dimension has anything to do with the number of hypothesis existed in a given space, could somebody please help me out?","Consider the following game:You pick n points, x_1 . . . x_n. Your adversary labels those n points as they want. Let's say for the sake of simplicity that the adversary applies binary classification, labeling each of the n points as either 0 or 1. You could express your adversary's labeling as a binary string in {0,1}^n, where the first bit in that labeling corresponds to the label of the first point, the second bit corresponding to the second point, etc. Call this binary string the hypothesis of your adversary.To win the game, you must propose a concept (in our case, a classifier), which describes a means by which you can match the hypothesis of your opponent.The VC dimension in this context is then the greatest number of points you can choose that will allow you to, regardless of thehypothesis,win against your opponent in the game. Knowing the hypothesis space H is important because it defines the space of all possible hypotheses that your opponent can put forth (in the case of the game, binary strings of length n). In order to be able to shatter k points, you need to be able to match all possible hypotheses by using a concept (classifier) in your concept space ('suitcase', as Tony endearingly puts it).Hope this helps!");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 2 Part A Questions b: How to define the operator X in this question? Is this Hadamard product?","It is actually just a product of two values.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Could I just write down answers to questions on a piece of paper and take a photo of it, and convert it to a pdf file? Editing formulas on computer is too time-consuming.","You can do that, but TA said if they cannot recognize your writing then you will receive 0 point.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 4, Submission: Should we only submit files that we've written?","yes");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("P3b - clarification: If we reached a dual solution which only involve inner-product of xi·xj, what are we expected to do in part b besides replacing it with F(x)i·F(x)j? is this enough or we need to work again from the Primary formula?","You can simply replace it.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("I'm wondering why the former 50 elements of the Y vector are all 1 and the later 50 elements of it are all 0. Shouldn't the labeling be random?","The data we gave you was sorted by class. You should, as the students' answer says, pick random testing and training sets.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Optimizer installation issues OSX 10.11: I can't seem to be able to install Steve Gunn's optimizer, I keep on getting error message:No supported compiler or SDK was found.I tried to change the SDK version to match my OS X version, as well as installing XCode, etc. - but still getting the same error.Was anyone able to install it under 10.11? If so - would appreciate your help.","You don't need to install anything (aside from Matlab, of course).  Just modify svc.m as the assignment indicates and use it to generate models for your SVMs.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("about SVM: Hi, I don't understand why the sum of the \alpha_i in the dual formulation of the sum  is equal to 1 (topic 6 slide 6, first time we see \alpha) according to the TA. And if so, why bother putting it in the expression to optimise?","I think you may have misunderstood my statements during OH. It's not that ?iai=1. In the linearly separable case that we were discussing, we have ?ji=0ai=?ni=j+1ai=1, where j splits the two classes.This is why we can say ?iaiYi=0, and is derived from the fact that a comes from the coordinate transform to barycentric coordinates.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("VC dimension of Perceptron Since we already have a perceptron can shatter d+1 points in Rd space, when proving that d+2 points cannot be shattered by the perceptron, do we just need to prove that the n+2 nd point has to be linearly dependent on the previous n+1 points?","You should provide a labeling for any d+2 that the perceptron can not realize.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("C value for Problem 4 in HW2 What values of C should we be testing?","You should try different C values.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 2b I've had a look at the class notes, but can't figure out what is required in this question.Can someone please point me to a starting point?","Hint: think about integrals");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Question 4: error is not changing Is error changing depending on the value of C? I use same code with "svc.m" and "svcerror.m" for linear SVM but it seems that error is not changing depending on the C. The other values except error like number of Support Vector are changing. Is anyone has same problem like this?","Have you replaced the y=0 labels in the Y with y=-1?");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("For Problem 1c, if Bob chooses two points A(12) and B(34) and labels them both +1, then Alice can't choose any classifier that would have the same labeling (c0 to c9 wouldn't classify both as +1). how can you resolve them in the case that the points don't share any common number? ","My understanding is that Alice gets to choose the points, then Bob gets to label them, then Alice chooses the classifier. ");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 3: Are we supposed to add the constraint or subtract it from the equation?","That is true, but the sign of your dual variables will depend on that decision. But both answers are correct. Usually we subtract the constraints though.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("HW2 Problem3 Hi, I am confused about what this problem is asking for. Should we just calculate the dual lagrange and parameters like w and alpha? What does "the solution to kernel regression" refer to?","In a) you should calculate the dual variables. In b) you should compute the expression of your predictor (basically the function you will use to make predictions)");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Question 4, plotting of loss In the question we are asked to show performance, In one of the earlier piazza discussions, the t.a said that we need to plot the loss. So which loss function do we have to use,least squares?","Plot the accuracy, or error of your classifier.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 4 : First part For the first part of Problem 4(trying different polynomials and RBF kernels with varying parameters), do we use the dataset (hw2-2015-dataset) provided OR can we use any arbitrary data?","use the dataset provided with the homework");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("hw2 problem 4 Robert mentioned we need plot 3D figure. However, I figured out for 2D plot, the result is more clear, i.e for different sigma, we 2D plot  error vs C. We can plot several 2D figures for different choice of sigma. Can we do like this? Or we must plot the 3D figure. Thanks.","You can plot several 2D figures instead.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("P1a - upper bound In the question it is quite possible to prove lower bound but upper bound seems quite hard to actually prove (even just for d=2 it requires some work...) - are we expected to officially prove the upper bound as well or just explain why it is difficult to shatter more points?","Please give a proof as rigorous as you can.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("problem 4: error in the svkernel.m When running svkernel.m, i get a matrix dimension error. Does anyone else get this and know how to fix it? ","Put this in your script before you run it. global p1 p1 = 2; % or whatever");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Question 1 c: Can we use an example to prove our answer?","For VC = k, I guess it's ok. But for VC != k+1, maybe not.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("code runs really slowly For some reason, my code takes forever to run everything. Is there a reason why or is there a way to fix it? ","Buy a faster computer maybe?");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Solutions of HW1 and HW2 Where can we find the solutions of both hw1 and hw2? I can't find them on Solution section in our websites or Coursework. ","They are on the course website, here: http://www.cs.columbia.edu/~jebara/4771/solutions.html");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("midterm Hi,Can someone clarify the materials for midterm please? Is it up to lecture 8 or...?Thanks","Yes, the midterm is comprehensive, anything we have covered so far in class is fair game for the midterm.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Is Kernel Logistic Regression Going to be Covered in Midterm Exam? Hi, is Kernel Logistic Regression Going to be Covered in Midterm Exam? Thanks.","Yes, anything we have covered in the class, in the homeworks, in the quizzes, etc. will be fair game for the midterm.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Cheatsheet for the midterm Is a 1 page cheat sheet (for formulae etc) allowed on the exam?","Sorry, there are no cheat sheets allowed. This is a closed book midterm and you can't access any notes. The only thing you can access during the midterm is a calculator (not a computer or smartphone).");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("HW03 Problem 3 In the third part of Problem 3: (a?b)?(b?c) Does the ? symbol means intersection in this case?","Yes, this is the symbol of logical AND.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Midterm sample question 2b Reposting another student's question from yesterday since we never got an answer...Can any one explain the answer of midterm sample question 2a ? Thanks !In addition, we never got a response to our request for an answer to 2b, which is missing from the answer key for the sample midterm. Anyone? Bueller? Bueller?","The order will matter. The margin will be different depending on the order.In the case where the kernel used is a linear kernel, e.g. k(xi,xj)=x?ixj, the kernelized algorithm should give the exact same results and updates as the non-kernelized algorithm. Do not derive gradient descent with the kernelized version, just look at how to implement the standard non-kernelized update rule where you store N alphas instead of D w values. The kernelized algorithm is just a different way of storing the model (and a different way of implementing the update rule and the prediction rule). In the linear case, both schemes (oriinal and kernelized) should be consistent (they produce the same mistakes and the same predictions).");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("For the midterm, will we be provided with scrap paper/should we bring scrap paper? ","Yes");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("practice midterm question 2a No one's really been able to explain this solution--does anyone know why online perceptron is used in the solution for 2a? Is there something in the problem that hints at that, and is that learning rule the only correct one?","The question gave you the update rule for the perceptron you are to use. Then it asked you to make a kernelized perceptron that emulates this update rule and generalizes it to the general kernel case (when the kernel is not just linear).");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Multi-layer neural networks Slide 14 of lecture 4 seems to indicate that a two-layer neural network can generate any convex region, while a three-layer network can generate nonconvex regions. Is it true that a two-layer network cannot generate a nonconvex region?","A two layer network can also generate nonconvex regions.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Every time I come to lecture, people keep talking about something called 'classifiers.'  What in the world is a classifier?Also, I've always been allowed to use multiplication tables on my previous exams.  Is it okay if I use my multiplication tables today?","A classifier is a function that, given a vector input, outputs a binary decision (either a 0 or 1 or, alternatively, a -1 or +1). We have developed several algorithms to learn good classifiers from training data. The algorithms include perceptrons, support vector machines, logistic regression, neural networks, etc.Also, no multiplication tables are allowed, but, you can definitely bring an abacus to the midterm.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("HW3, Question 1 I can't understand part 1 of question 1 completely. Does it mean if after N rounds we conclude that the dice is most likely unfair, (which is defined when the probability that both dices are loaded is >= 0.5 ??), what is the minimum number of wins?!Thanks. ","The questions asks the minimum number of plays you have to observe, so it is possible to reach the conclusion that the dice are loaded. Notice that, even if the dice are indeed loaded, this will not necessarily happen in the minimum number of plays. It depends on the outcomes.The question ask what is this minimum number of plays and when is it sufficient to detect that the dice are not fair (which are the outcomes that allow us to do this inference in the minimum number of plays).");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 2 I got a bit confused with notation in this problem. p means pdf where P means probability itself. So I cannot understand why the question uses p(H) instead of P(H), because the way I'm looking at it is given \mu, probability of head is \mu, however I know the prior distribution of \mu, so P(H) is average \mu... right?Thanks","In the homework description we are using p(H) as the probability of heads. In other words, we are using p interchangeably for pdfs and probabilities.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Convex problems Hi all, I believe it would be interesting for everyone if we listed below all the convex minimisation (or concave maximisation) we've encountered so far in ML with some justifications for each example (as to why it is convex). Thanks all for your contribution (or any TA also)","I believe all optimization problems you have seen in class so far are convex/concave. A way of showing that is, for example, to take the likelihood and compute it's Hessian (equivalent to the second derivative). If can show that the Hessian is always negative definite, then you know the likelihood is strictly concave. Instead of maximizing the likelihood, you can minimize the negative likelihood, which is a convex optimization problem.You can do this to show that linear regression and logistic regression (with or without regularization) are convex problems. For SVM, there are other ways to show it's convexity, but it is also a convex problem.Perhaps the first non-convex roblem you will see in class is fitting mixtures of Gaussians. Because this is a non-convex problem, you will need to use the EM algorithm to try to solve it.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Too large data for problem 5 of hw3? When I computed  the RBF kernel parameter ?, it took very long time.  In fact, training data TrainingX is of size 1000*784, so the  running time for  ? is at least 784*10^6.  I wonder whether it is possible to do all the computation.","It should be reasonable if you vectorize your operations (as opposed to using for loops in MATLAB). Here's some links that could help: http://www.mathworks.com/help/matlab/matlab_prog/vectorization.html http://www.mathworks.com/help/matlab/matlab_prog/techniques-for-improving-performance.html As a general rule of thumb, a modern processor has at least ~25 GFLOPS per core (e.g., 25×109 floating-point operations (meaning add/subtract/divide/multiply)) per second. Thus, the operation should complete fairly quickly.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Homework 3, Question 2 Relatively simple question: how should we factor showing our work into the instructions in question 2 to provide our answers in a table?","I am not sure I understand your question. You should show your calculations, and you should put your final answers in a table. Does this answer your question?");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("HW3 question 1 part 2 outcomes of the dice: Are we supposed to show the numbers on the dice or just if the round is a win?","Just if the round is a win.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("HW3 Problem 5 After it finishes gradient descent with Test data, I ran the prediction with Training data. However, out of 1000 prediction there are about 450 wrong decisions. The error rate seems to high. Is it normal?","Check your functions again, I had this problem since I mistakenly calculated norm to compute kernels (I took square root) After fixing this I got about 10% error. Also, step size is very important, monitor norm of gradient at each iteration to find a good and reasonable interval for step size.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("HW3 Q2 clarification I want to make sure that µML means the maximum likelihood estimation given the data and not considering the prior distribution correct?  And µMAP means the maximum likelihood estimation taking into account the prior and the data?Also P(H | D) means evaluating P(H) using P(µ|D) correct?","Yes, Yes and Yes.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Looking up solutions online.I was just wondering if the academic honesty policy is strictly enforced. I often struggle with questions and am forced to submit partial solution or submit late. At the same time, I know of some students who just copy the answers posted online to the questions getting full marks in home-work.","Academic honesty policy is always strictly enforced. If you know of students who are cheating in any way, please let us know so that we can investigate.For those of you who may have considered doing things like this: the homework is intended to exercise your understanding of concepts and techniques learned in class. Cheating on the homework -- even if you never get caught -- is only cheating yourself of learning, which will show on quizzes and exams.If you are stuck on the homework, please come to office hours and/or post your questions to Piazza. Also, it's probably in your best interest to start as early as possible.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 5 Hi,For problem 5, for SGD, converge means minimum of J(w) converges?Since the norm between wt+1 and w seems hard to fall below 0.01.","The assignment description explains what are the two stopping criteria you should use. Please take a look there and see if it answers your question.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Question 2 Could someone please give a hint as to what concepts we need to use for this question I find myself completely stuck with this one","What part are you stuck on?It is usually useful to remember common laws of probability, e.g. law of total probability and Bayes' rule. It's also useful to think about what kinds of distributions there are in the problem, and whether any of them are familiar.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("P5 - Grad Descent stuck at 30%
My Gradient Descent coverges nicely but stuck at 30% with all different step sizes smaller than 0.5 When I check the error I see all the errors are false positive - it never gets any positive answer wrong but more than half of negative answers are predicted wrong - so to be clear in the beginning my algo guess everything as positive (exactly 50% error) - and within short time guesses 40% of negative answers right but can't get better.Even more interesting - when changing ETA to be 0.5 - I am getting 9% error after 1 step!! but then then each step error rate interleave between 9% and 33% and algo don't converge (grad switch side all the time)?Is this problem with evaluation / derivation? or am I stuck at local minima?","There is a problem with your derivation.Also there seems to be confusion in your reasoning.You can't get "stuck in a local minima", since the cost function is convex. Therefore, using gradient descent, your algorithm should converge to the unique optimal parameter w* minimizing the cost function whenever the step size is small enough.The test accuracy should not vary too much once you are close enough to this optimal parameter.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Is there any way we can see our graded homeworks to know what we lost points on? Right now, CourseWorks only shows the total score, not even a breakdown by question, so I wouldn't even know which TA to ask what I lost points for.","This is strange, the details of the grading should appear in the comments. I already discussed the grading with some students who had access to it.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Step size in problem 5 I find that the reasonable step size for Gradient descend and SGD  is quite different. The step size for Gradient descend is around 95, for SGD  p =100 is around 9, and for SGD p =1 is around 0.001.  With this step sizes, the algorithm will obtain a good model in 10 to 15 seconds.In the final part of the problem, it asked us to plot the figure of the three different methods simultaneously for comparison of speed. But should we use different step sizes for each method as above, or have to use the same sizes?","Different step sizes. Use the best for each method");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("For the gradient descent(not SGD) in problem 5, do we only record the cost for 5-10 seconds as well? Since the iterations could take longer than 5-10 seconds to get a gradient less than the epsilon.","Please read the instructions carefully. Yes, you should record the cost for 5-10 seconds for all three methods.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Problem 5 When to update W For gradient descent and SGD, do we update W for each training data, or do we only update when we have mis-classified point, i.e. we need check for the result before updating W?","You should compute the gradient regardless of the point being correctly classified or not.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("In the homework assignments, unless specified otherwise, log(x) means natural log of x, right?","Yes. But also, sometimes it just doesn't matter. If you are maximizing log-likelihood, it actually doesn't matter the base of the log.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("I'm stuck finding the variance of the posterior distribution.This is the formula that I've been using: Var(X) = E[X^2] - (E[X])^2 and E[X] = integral of X * p(X) dX.Is this the right direction?","Yes. You are on the right track!");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Homework 3 Problem 2 For problem 2 with distribution(B) (i.e. probability distribution which has the form of a concave parabola with its maximum at 12 and falls to 0 at 0 and 1), if I identify the distribution as a well known distribution, do I need to derive the proof for each part as well?","If you identify the distribution you can use known facts from the distribution. Just cite your sources.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("Does SGD necessarily use less time to reach the minimum cost comparing to gradient descent? I feel like it really depends on the step size. If the step size is large, SGD reaches the minimum pretty fast, however, it may have higher uncertainties associated with the accuracy. On the other hand, choosing a small step size takes longer time, but the result tends to be more stable.","It depends on the step size.");
INSERT INTO Intellibot.TrainingData(question,answer) VALUES("","");
